# Generated by Django 4.2.6 on 2023-10-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0002_remove_certificate_expiry_certificate_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
